Fix the clang format workflow
oomph-lib/oomph-lib pull request #129
Opened 2024-10-18 10:24 UTC by PaulAlexander23

Using the latest version of ubuntu causes and issue with the clang format workflow.
I've fixed the issue and completed a pull request such that the latest of Puneet's workflows includes the fix.
If the tests pass then the fix has worked.
There might also be an issue with Python2 (needed for installing trilinos) for the latest Ubuntu version 24.04.1.

2024-10-18 10:25 UTC, PaulAlexander23 commented
Converted to a draft until the tests pass.

2024-10-21 12:32 UTC, PaulAlexander23 commented
Added tests to run on Ubuntu 22.04.

2024-10-21 13:34 UTC, puneetmatharu requested changes
Thanks for creating a PR to handle this, but I think we can use a much simpler approach IF we want to truly test on multiple OS versions (which includes burning more fossil fuels to run the self-tests). @MatthiasHeilManchester do you have any opinions on this?

2024-10-21 13:34 UTC, puneetmatharu commented on .github/workflows/clang-format.yaml
> +      - uses: PuneetMatharu/clang-format-lint-action@master
Use `v0.18`, not the branch name.

2024-10-21 13:34 UTC, puneetmatharu commented on .github/workflows/self-tests-ubuntu-22-04.yaml
> +name: Ubuntu 22.04 self-tests
This is _not_ the way to run self-tests on multiple versions of Ubuntu. Creating a new workflow file creates a large amount of code duplication. We also don't want things to diverge between the different Ubuntu-target self-test workflows, and thus have to manage twice as many workflows. Look at using a [matrix](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#using-a-matrix-strategy).

2024-10-21 13:34 UTC, puneetmatharu commented on README.md
> +        <td>Ubuntu Latest (24.04)</td>
Please undo the changes in the README. We can just test for multiple OS versions within the same workflow and group it under Linux.

2024-10-22 13:14 UTC, puneetmatharu commented
Great. Thank you!

2024-10-22 13:14 UTC, merged

2024-10-22 17:16 UTC, MatthiasHeilManchester commented
Just catching up with this... Agree that we should try to keep things going with the latest ubuntu (though I've heard bad things about it and was told not to upgrade...). 

Googled around a bit and found a long discussion here:

https://github.com/actions/setup-python/issues/672

which suggests this:

runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster

Don't understand it well enough to be able to comment...

   m.